import {EN_EXTRA} from "./i18n-extra.ts";
import {EN_INTERFACE, UI_MESSAGES} from "./i18n-ui.ts";
export type Locale = "pl" | "en";
export const EN: Record<string,string> = {
  "Edytuj": "Edit",
  "Edytuj zapis leku.": "Edit medication record.",
  "Popraw nazwę, zapisaną dawkę lub datę rozpoczęcia.": "Correct the name, recorded dose or start date.",
  "To korekta Twojego zapisu. Plan dawek i godziny edytujesz w planie dnia.": "This corrects your record. Edit dose schedules and times in your daily plan.",
  "Zapisz zmiany": "Save changes",
  "Dane leku zaktualizowane.": "Medication record updated.",
  "Nie udało się zaktualizować leku. Spróbuj ponownie.": "Unable to update the medication. Try again.",
  "Data rozpoczęcia nie może być wcześniejsza niż zapis samopoczucia sprzed leku.": "The start date cannot be earlier than the recorded baseline.",
  ...EN_EXTRA,
  ...EN_INTERFACE,
  "Leki":"Medications", "Historia":"History", "Wiedza":"Evidence", "Cykl":"Cycle", "Konto":"Account", "Ustawienia":"Settings",
  "Twój osobisty dziennik":"Your personal journal", "Twój dziennik":"Your journal", "Dodaj lek":"Add medication", "Czuję zmianę":"I feel different", "Zapisz punkt wyjścia":"Record baseline", "Twoje leki":"Your medications", "Twoje leki.":"Your medications.", "Twoja perspektywa.":"Your perspective.",
  "Małe obserwacje. Twoja historia.":"Small observations. Your story.", "Twój osobisty przebieg":"Your personal timeline", "Każdy zapis":"Every entry", "ma swoje miejsce.":"has a place.", "Ostatnio u Ciebie":"Your recent observations", "Wszystkie obserwacje":"All observations",
  "Miejsce na nowy lek.":"Room for a new medication.", "Zapisz nazwę, dawkę i datę rozpoczęcia. Potem dodasz krótkie samopoczucie sprzed leczenia.":"Record the name, dose and start date, then add a brief baseline.", "Co się zmieniło?":"What changed?", "Twój punkt wyjścia.":"Your starting point.",
  "Nazwa leku":"Medication name", "Nazwa z opakowania":"Name on the packaging", "Dawka":"Dose", "Np. 10 mg":"e.g. 10 mg", "Data rozpoczęcia":"Start date", "Zapisz lek":"Save medication", "Data obserwacji":"Observation date", "Jak się czułaś przed rozpoczęciem?":"How did you feel before starting?", "Krótka notatka o Twoim samopoczuciu":"A brief note about how you felt", "Zapisz samopoczucie przed lekiem":"Save baseline",
  "Objaw lub zmiana":"Symptom or change", "Opisz własną obserwację":"Describe your observation", "Nasilenie — Twoja ocena":"Severity — your rating", "Wybierz 1–5":"Choose 1–5", "1 / 5 — niewielkie":"1 / 5 — mild", "5 / 5 — duże":"5 / 5 — strong", "Kiedy się pojawił?":"When did it start?", "Notatka":"Note", "(opcjonalnie)":"(optional)", "Co chcesz zapamiętać?":"What would you like to remember?", "Zapisz obserwację":"Save observation", "Zapisuję…":"Saving…", "Zamknij panel":"Close panel",
  "Cykl jako kontekst":"Cycle context", "Więcej miejsca":"More room", "na Twoje ciało.":"for your body.", "Zajrzyj do cyklu":"Explore your cycle", "Co wiemy":"What do we know", "o Twoim leku?":"about your medication?", "Zobacz informacje":"View evidence", "Twoja historia obok informacji z oficjalnych źródeł. Z jasnymi ograniczeniami.":"Your story alongside official information, with clear limitations.",
  "Pierwszy krok":"First step", "Zacznij od swojego leku.":"Start with your medication.", "Nazwa, dawka i data. Resztę historii zbudujesz własnymi obserwacjami.":"Name, dose and date. Build the rest with your own observations.", "Twoja historia":"Your story", "zaczyna się tutaj.":"starts here.", "Dodaj kontekst":"Add context", "Rozpoczęcie leku":"Medication started", "Samopoczucie przed rozpoczęciem":"Baseline", "Twój zapis":"Your entry", "Twój zapis · przed lekiem":"Your entry · baseline", "Twój dziennik leku":"Your medication journal", "Obserwowany lek":"Selected medication", "Zapis rozpoczęcia:":"Start recorded:", "Samopoczucie przed rozpoczęciem zapisane":"Baseline recorded", "Zacznij od samopoczucia przed rozpoczęciem":"Start by recording your baseline",
  "Źródła i Twoje obserwacje":"Sources and your observations", "Co wiemy?":"What do we know?", "Spójrzmy osobno.":"Let’s look separately.", "Twoje doświadczenie":"Your experience", "Oficjalne informacje":"Official information", "Zgłoszenia z praktyki":"Real-world reports", "Ograniczenia":"Limitations", "TWOJE DOŚWIADCZENIE":"YOUR EXPERIENCE", "OFICJALNE INFORMACJE":"OFFICIAL INFORMATION", "ZGŁOSZENIA Z PRAKTYKI":"REAL-WORLD REPORTS", "OGRANICZENIA":"LIMITATIONS", "Twoja historia. Twoje słowa.":"Your story. Your words.", "Informacje u źródła.":"Information at its source.", "Raporty, z kontekstem.":"Reports, with context.", "Czego nie wiemy.":"What we don’t know.", "Przed rozpoczęciem leku":"Before starting medication", "Wróć do historii":"Back to history", "Niewystarczające informacje":"Insufficient information", "Wyróżnione ostrzeżenie (boxed warning)":"Boxed warning", "Ostrzeżenia":"Warnings", "Ostrzeżenia i środki ostrożności":"Warnings and precautions", "Działania niepożądane — tekst etykiety":"Adverse reactions — label text", "Oryginalne informacje FDA":"Original FDA information", "Pełny tekst tej sekcji · bez podziału":"Full original section", "Otwórz źródło etykiety":"Open label source", "Otwórz wyszukiwanie źródłowe":"Open source lookup", "Płeć zapisana w zgłoszeniach":"Sex recorded in reports", "Kobiety":"Female", "Mężczyźni":"Male", "Nieznana":"Unknown", "raportów":"reports",
  "Ciało ma swój rytm":"Your body has a rhythm", "Więcej kontekstu.":"More context.", "Bliżej siebie.":"Closer to yourself.", "Twój cykl.":"Your cycle.", "Twój kontekst.":"Your context.", "Od Twojego zapisu":"From your recorded date", "Chwila dla siebie.":"A moment for yourself.", "Nastrój":"Mood", "Energia":"Energy", "Sen":"Sleep", "Nawodnienie":"Hydration", "Dodaj zapis samopoczucia":"Add check-in", "Zapisz samopoczucie":"Save check-in", "Jak minął Twój dzień?":"How was your day?", "Pierwszy dzień krwawienia":"First day of bleeding", "Ostatni dzień (opcjonalnie)":"Last day (optional)", "Zaobserwowane krwawienie (opcjonalnie)":"Observed flow (optional)", "Bez zapisu":"Not recorded", "Zapisz daty krwawienia":"Save bleeding dates", "Twój zapis krwawienia.":"Your bleeding record.", "Zapisane daty":"Recorded dates", "Twój zapis cyklu.":"Your cycle record.", "Daty i obserwacje":"Dates and observations", "To, co zauważyłaś.":"What you noticed.", "Twój zapis samopoczucia":"Your check-in", "Sen — liczba godzin (opcjonalnie)":"Sleep — hours (optional)", "Nastrój — Twoja ocena":"Mood — your rating", "Picie wody w porównaniu ze zwykłym dniem":"Water intake compared with a usual day", "Co jeszcze chcesz zapisać? (opcjonalnie)":"Anything else to record? (optional)", "1 = bardzo niski, 5 = bardzo dobry":"1 = very low, 5 = very good", "1 = bardzo niska, 5 = bardzo wysoka":"1 = very low, 5 = very high",
  "Mapa Twojego cyklu.":"Your cycle map.", "Zapisy i orientacja":"Records and orientation", "Twoje obserwacje":"Your observations", "Orientacyjny model":"Calendar estimate", "Sprawdź dzień":"Explore a day", "Zapisane krwawienie":"Recorded bleeding", "Krwawienie zapisane przez Ciebie.":"Bleeding recorded by you.", "Orientacyjne okno możliwej płodności":"Illustrative possible fertile window", "Zakres możliwej owulacji":"Possible ovulation range", "Orientacyjny etap":"Estimated phase", "Możliwa owulacja · zakres":"Possible ovulation · range", "Płodność tego dnia":"Fertility on this day", "Nie wskazujemy jednego dnia jako pewnej daty owulacji.":"No single day is a confirmed ovulation date.", "Nie określamy prawdopodobieństwa ciąży. Poza tym zakresem ciąża nadal jest możliwa.":"We do not estimate pregnancy probability. Pregnancy remains possible outside this range.", "Niewystarczające informacje do szacunku":"Insufficient information for an estimate", "Owulacja, płodność i etap hormonalny: nieznane.":"Ovulation, fertility and hormonal stage: unknown.", "Ta mapa nie jest metodą antykoncepcji ani narzędziem planowania ciąży. Nie pokazuje „bezpiecznych dni”.":"This map is not contraception or a pregnancy-planning tool. It does not show safe days.", "Samopoczucie też ma kontekst.":"Wellbeing has context too.", "Zapisz kontekst cyklu":"Save cycle context", "Określ kontekst cyklu":"Set cycle context", "Sprawdź kontekst cyklu":"Review cycle context", "Kontekst ma znaczenie.":"Context matters.", "Który opis pasuje obecnie do Twojej sytuacji?":"Which description currently fits your situation?", "Nie wiem / pokazuj tylko moje zapisy":"Unsure / show records only", "Hormony, nieregularne cykle lub inny wpływ na cykl":"Hormones, irregular cycles or another influence", "Regularne, naturalne cykle — chcę szacunek kalendarzowy":"Regular natural cycles — show calendar estimates",
  "Twoja obserwacja":"Your observation", "Małe pytania.":"Small questions.", "Tylko to, co wiesz":"Only what you know", "Twoje odpowiedzi":"Your answers", "Wybierz tak, nie lub nie jestem pewna. Możesz pozostawić pytanie bez odpowiedzi.":"Choose yes, no or unsure. You can leave any question unanswered.", "Bez odpowiedzi":"Unanswered", "Tak":"Yes", "Nie":"No", "Nie jestem pewna":"Unsure", "Zapisz odpowiedzi":"Save answers", "Odpowiedzi zapisane.":"Answers saved.", "Pomiń pytania i wróć do leków →":"Skip questions and return to medications →", "← Twoje leki":"← Your medications", "Obserwacja zapisana. Możesz teraz dodać kontekst — to opcjonalne.":"Observation saved. Adding context is optional.",
  "niewielkie":"light", "umiarkowane":"medium", "obfite":"heavy", "nie jestem pewna":"unsure", "mniej niż zwykle":"less than usual", "jak zwykle":"usual", "więcej niż zwykle":"more than usual",
  "Dzisiejszy plan":"Today’s plan", "Jedna dawka na raz.":"One dose at a time.", "Ustaw plan":"Set schedule", "Skanuj receptę":"Scan prescription", "Podsumowanie dla lekarza":"Clinician summary", "Pobierz PDF":"Download PDF", "Plan i przypomnienia":"Schedule and reminders", "Przyjęłam":"Taken", "Cofnij oznaczenie":"Undo check", "Godzina dawki":"Dose time", "Godzina przypomnienia":"Reminder time", "Zapisz plan":"Save schedule", "Koniec planu (opcjonalnie)":"Schedule end (optional)", "Zatrzymaj plan":"Pause schedule", "Wznów plan":"Resume schedule", "Nazwa konta":"Display name", "Język":"Language", "Wygląd":"Appearance", "Jasny":"Light", "Ciemny":"Dark", "Jak w systemie":"System", "Strefa czasowa":"Time zone", "Zapisz ustawienia":"Save settings", "Wyloguj się":"Sign out", "Zmień hasło":"Change password", "Obecne hasło":"Current password", "Nowe hasło":"New password", "Zaloguj się":"Sign in", "Załóż konto":"Create account", "E-mail":"Email", "Hasło":"Password", "Imię":"Name", "Twoja przestrzeń.":"Your own space.", "Wszystko w jednym miejscu.":"Everything in one place.", "Osobisty dziennik":"Personal journal", "Dostęp do danych":"Data access", "Ustawienia zapisane.":"Settings saved.", "Szukaj objawu":"Search a symptom", "Objawy w etykiecie":"Symptoms in the label", "Dopasowanie Twojego opisu":"Your description matches", "Cytat z etykiety":"Label quote", "Otwórz pełny kontekst":"Open full context", "Nie znaleziono dopasowania":"No matching text found", "To nie wyklucza działania leku.":"This does not rule out a medication effect.", "Zapisz szkic recepty":"Save prescription draft", "Sprawdź każdy lek i potwierdź":"Review each medication and confirm", "Tekst odczytany ze zdjęcia":"Text read from the image", "Nie zapisujemy zdjęcia recepty.":"We do not store the prescription image.", "Usuń pozycję":"Remove item", "Dodaj pozycję":"Add item", "Potwierdzam zgodność z receptą":"I confirm these details match the prescription", "Wybierz zdjęcie":"Choose image", "Odczytaj zdjęcie":"Read image", "Nieznane":"Unknown", "Wystąpił błąd. Spróbuj ponownie.":"Something went wrong. Try again.",
};
export function translate(text:string,locale:Locale):string {
 if(Object.hasOwn(UI_MESSAGES,text))return UI_MESSAGES[text][locale];
 if(locale!=="en")return text;if(Object.hasOwn(EN,text))return EN[text];
 // Only applied by UI text components; never applied to user-entered symptom or note fields.
 const replacements:Array<[RegExp,string]>=[
  [/^Dzień (\d+) od zapisanego początku krwawienia(; krwawienie zapisane)?\.?$/,"Day $1 from recorded bleeding start$2"],
  [/^Dzień (\d+) od zapisanego początku$/,"Day $1 from recorded start"],
  [/^Jak czułaś się przed rozpoczęciem (.+)\? Krótki zapis nada kontekst kolejnym obserwacjom\.$/,"How did you feel before starting $1? A brief baseline gives context to later observations."],
  [/^Twoja obserwacja dla (.+)\. Zapisz ją własnymi słowami\.$/,"Your observation for $1. Record it in your own words."],
  [/^Od zapisanego początku krwawienia: (.+)\.$/,"From the recorded bleeding start: $1."],
  [/^Początek krwawienia: (.+)\.$/,"Bleeding start: $1."],
  [/^Ostatni zapis samopoczucia: (.+)$/,"Last check-in: $1"],
  [/^Ostatni zapisany dzień: (.+)$/,"Last recorded day: $1"],
  [/^Twój zapis samopoczucia: picie wody — (.+)\.$/,"Your check-in: water intake - $1."],
  [/^Twój zapis samopoczucia: sen — (.+) godzin\.$/,"Your check-in: sleep - $1 hours."],
  [/^Twój zapis samopoczucia: nastrój — (.+)\.$/,"Your check-in: mood - $1."],
  [/^Twój zapis samopoczucia: energia — (.+)\.$/,"Your check-in: energy - $1."],
  [/^Nastrój (.+)$/,"Mood $1"],[/^Energia (.+)$/,"Energy $1"],[/^Sen (.+)$/,"Sleep $1"],[/^Woda: (.+)$/,"Water: $1"],
 ];
 for(const [pattern,replacement] of replacements)if(pattern.test(text))return text.replace(pattern,replacement).replace("; krwawienie zapisane","; bleeding recorded");
 return text;
}
