"use client";
import {useState} from "react";
import {authenticate} from "@/app/account-actions";
import {SaveButton} from "./save-button";
import {useT} from "./preferences-provider";
export function AuthForm({hasJournal}:{hasJournal:boolean}) {
  const [mode,setMode]=useState("login"), t=useT();
  return <><div className="auth-tabs"><button type="button" aria-pressed={mode==="login"} onClick={()=>setMode("login")}>{t("Zaloguj się")}</button><button type="button" aria-pressed={mode==="register"} onClick={()=>setMode("register")}>{t("Załóż konto")}</button></div><form action={authenticate} className="space-y-5"><input type="hidden" name="mode" value={mode}/>{mode==="register"&&<div><label htmlFor="auth-name" className="label">{t("Imię")}</label><input id="auth-name" name="display_name" required maxLength={80} autoComplete="given-name" className="input"/></div>}<div><label htmlFor="auth-email" className="label">{t("E-mail")}</label><input id="auth-email" name="email" type="email" required maxLength={254} autoComplete="email" className="input"/></div><div><label htmlFor="auth-password" className="label">{t("Hasło")}</label><input id="auth-password" name="password" type="password" required minLength={12} maxLength={128} autoComplete={mode==="register"?"new-password":"current-password"} className="input"/><p className="section-copy">12–128 {t("Język")==="Language"?"characters":"znaków"}</p></div>{mode==="register"&&hasJournal&&<label className="profile-confirmation"><input type="checkbox" name="import_journal"/><span>{t("Język")==="Language"?"Attach my existing journal from this browser to this new account. I confirm it contains my records.":"Przenieś mój dotychczasowy dziennik z tej przeglądarki do nowego konta. Potwierdzam, że to moje zapisy."}</span></label>}<SaveButton>{t(mode==="register"?"Załóż konto":"Zaloguj się")}</SaveButton></form><p className="section-copy mt-5">{t("Język")==="Language"?"Local demo: email verification and forgotten-password recovery are not connected yet.":"Wersja lokalna: weryfikacja e-maila i odzyskiwanie zapomnianego hasła nie są jeszcze podłączone."}</p></>;
}
