"use client";
import Link from "next/link";
import {useEffect,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {setTaken} from "@/app/daily-actions";
import {localDate,localTime,type DailyDose} from "@/lib/daily";
import {useT,useLocale} from "./preferences-provider";
import {Icon} from "./icon";
export function DailyPlan({doses,date,timezone}:{doses:DailyDose[];date:string;timezone:string}) {
 const t=useT(),locale=useLocale(),router=useRouter(),[clock,setClock]=useState<string|null>(null),[pending,start]=useTransition(),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const update=()=>{setClock(localTime(timezone));if(localDate(timezone)!==date)router.refresh();};update();const timer=setInterval(update,30000);const visible=()=>{if(!document.hidden){update();router.refresh();}};document.addEventListener("visibilitychange",visible);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",visible);};},[date,timezone,router]);
 const completed=doses.filter(d=>d.taken_at).length;
 function toggle(dose:DailyDose){setBusy(dose.id);setError(false);start(async()=>{try{const form=new FormData();form.set("schedule_id",dose.id);form.set("due_on",date);form.set("taken",dose.taken_at?"false":"true");await setTaken(form);router.refresh();}catch{setError(true);}finally{setBusy(null);}});}
 return <section className="daily-plan" aria-labelledby="daily-title"><div className="section-heading"><div><p className="eyebrow">{t("Dzisiejszy plan")} · {new Intl.DateTimeFormat(locale==="en"?"en-GB":"pl-PL",{day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(date+"T12:00:00Z"))}</p><h2 id="daily-title">{t("Jedna dawka na raz.")}</h2></div><Link href="/schedule" className="text-button">{t("Ustaw plan")}<Icon name="plus"/></Link></div>{doses.length>0&&<div className="daily-progress"><div style={{width:`${completed/doses.length*100}%`}}/><span>{completed}/{doses.length} {locale==="en"?"marked taken":"oznaczonych jako przyjęte"}</span></div>}{error&&<p role="alert" className="notice-error">{t("Wystąpił błąd. Spróbuj ponownie.")}</p>}<div className="daily-list">{doses.map(dose=><article key={dose.id} className={`daily-dose ${dose.taken_at?"taken":""}`}><time>{dose.take_time}</time><div><strong>{dose.name}</strong><p>{dose.dose}</p>{dose.taken_at?<small>{locale==="en"?"Recorded at":"Zapisano o"} {new Intl.DateTimeFormat(locale==="en"?"en-GB":"pl-PL",{hour:"2-digit",minute:"2-digit",timeZone:timezone}).format(new Date(dose.taken_at))}</small>:dose.remind_time&&<small className={clock&&clock>=dose.remind_time?"reminder-due":""}>{locale==="en"?"Reminder":"Przypomnienie"} {dose.remind_time}{clock&&clock>=dose.remind_time?(locale==="en"?" · pending":" · oczekuje"):""}</small>}</div><button type="button" disabled={pending&&busy===dose.id} className="dose-check" aria-pressed={Boolean(dose.taken_at)} aria-label={`${t(dose.taken_at?"Cofnij oznaczenie":"Przyjęłam")} · ${dose.name} · ${dose.take_time}`} onClick={()=>toggle(dose)}><Icon name={dose.taken_at?"check":"plus"}/></button></article>)}</div>{!doses.length&&<p className="section-copy">{locale==="en"?"Add the schedule you were prescribed. We do not choose a dose or timing for you.":"Dodaj godziny zgodne z otrzymanym zaleceniem. Aplikacja nie dobiera dawki ani godzin przyjmowania."}</p>}<p className="section-foot">{locale==="en"?`Your own adherence record · ${timezone}. An unchecked dose does not mean you should take it now. No missed-dose instructions.`:`Twój zapis przyjęcia · ${timezone}. Brak oznaczenia nie jest zaleceniem przyjęcia dawki teraz. Nie podajemy instrukcji postępowania z pominiętą dawką.`}</p></section>;
}
