"use client";
import {useEffect,useState} from "react";
import {useLocale} from "./preferences-provider";
export function PushSettings() {
 const en=useLocale()==="en",[supported,setSupported]=useState<boolean|null>(null),[key,setKey]=useState<string|null>(null),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{setSupported("serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window&&window.isSecureContext);fetch("/api/push").then(r=>r.ok?r.json():null).then(data=>{if(data){setKey(data.publicKey);setEnabled(data.subscribed);}}).catch(()=>setError(en?"Could not load notification settings.":"Nie udało się wczytać ustawień powiadomień."));},[en]);
 async function toggle(){setBusy(true);setError("");try{
  if(enabled){const result=await fetch("/api/push",{method:"DELETE"});if(!result.ok)throw Error();const registration=await navigator.serviceWorker.getRegistration();await (await registration?.pushManager.getSubscription())?.unsubscribe();setEnabled(false);return;}
  if(!key)return;
  const permission=await Notification.requestPermission();if(permission!=="granted"){setError(en?"Notifications were not enabled. You can still use the daily checklist.":"Powiadomienia nie zostały włączone. Nadal możesz używać planu dnia.");return;}
  const registration=await navigator.serviceWorker.register("/reminders-sw.js");await navigator.serviceWorker.ready;
  const bytes=Uint8Array.from(atob(key.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));
  const subscription=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});
  const result=await fetch("/api/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription.toJSON())});if(!result.ok)throw Error();setEnabled(true);
 }catch{setError(en?"Could not enable notifications in this browser. The daily checklist still works.":"Nie udało się włączyć powiadomień w tej przeglądarce. Plan dnia nadal działa.");}finally{setBusy(false);}}
 return <section className="card"><p className="eyebrow">{en?"A gentle reminder":"Dyskretne przypomnienie"}</p><h2 className="section-title mt-3">{en?"Browser notifications.":"Powiadomienia przeglądarki."}</h2><p className="section-copy">{en?"Optional push reminders, with no drug name or dose on the lock screen. Your browser’s notification service receives a generic reminder and a subscription token.":"Opcjonalne powiadomienia bez nazwy leku i dawki na ekranie blokady. Usługa powiadomień przeglądarki otrzymuje ogólne przypomnienie i token subskrypcji."}</p>{supported===false&&<p className="notice-attention">{en?"This browser does not support push here. Use Chrome, Edge or Firefox on localhost / HTTPS. The daily checklist is available.":"Ta przeglądarka nie obsługuje tu powiadomień. Użyj Chrome, Edge lub Firefox na localhost / HTTPS. Lista dawek jest dostępna."}</p>}{supported&& !key&&<p className="notice-attention">{en?"Push delivery is not configured yet. Your reminders remain visible in the daily plan.":"Wysyłanie powiadomień nie jest jeszcze skonfigurowane. Przypomnienia pozostają widoczne w planie dnia."}</p>}{supported&&key&&<button type="button" className="button-secondary" disabled={busy} onClick={toggle}>{en?(enabled?"Disable notifications on this device":"Enable notifications on this device"):(enabled?"Wyłącz powiadomienia na tym urządzeniu":"Włącz powiadomienia na tym urządzeniu")}</button>}{error&&<p role="alert" className="notice-error mt-4">{error}</p>}<p className="section-copy mt-4">{en?"Delivery requires the reminder worker and browser permission. Device restrictions may delay or block it. This is not an alarm service for critical doses.":"Wysyłka wymaga działającego procesu przypomnień i zgody przeglądarki. Ograniczenia urządzenia mogą ją opóźnić lub zablokować. To nie jest alarm dla dawek wymagających niezawodnego powiadomienia."}</p></section>;
}
